### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by joeyhipolito** [IonicaBizau/git-stats-importer#32]
Ubuntu 14.04
no output,
cannot read email in .gitconfig

**Comment by IonicaBizau** [comment]
Does `echo $GIT_AUTHOR_EMAIL` output something?

You can specify the emails using `-e`:

```sh
git-stats-importer -e 'you@domain.com, you@example.com'
```

**Comment by joeyhipolito** [comment]
yes, I added -e parameter like that..
git-stats-importer -e "joey@example.com"

I even tried to run your app example, no output..no stdout..

**Comment by IonicaBizau** [comment]
@joeyhipolito Hmm, let's suppose your email address is `you@example.com`. If you do in your repository (you want to import):

```sh
$ git log --author '<you@example.com>'
```

You should see the commits? How many commits you see there?

**Comment by joeyhipolito** [comment]
about 897..I did..


    git rev-list HEAD --author='joey@example.com' --count

**Comment by IonicaBizau** [comment]
Whoups, actually I'm reproducing this here... Let me investigate.

**Comment by joeyhipolito** [comment]
sure :+1:

**Comment by IonicaBizau** [comment]
Addressed in https://github.com/IonicaBizau/git-stats/pull/72 and :ship: **`git-stats@2.6.0`** :tada: 
Since, `git-stats-importer` uses `git-stats@^2.0.0`, you should be able to just `npm i -g git-stats-importer@latest` and the `git-stats` dependency will be automatically updated. :sparkle: 

Thanks for heads-up! :cake:

**Comment by joeyhipolito** [comment]
still not working somehow..i will reinstall both git-stats and git-stats-importer..latest... and see if it'll work

**Comment by IonicaBizau** [comment]
Please double check the output of `npm i -g git-stats-importer@latest`
(especially the `git-stats` dependency version).
It should be `git-stats@2.6.0`.

Otherwise, we will force the dependency version to be higher than 2.6.0.

**Comment by joeyhipolito** [comment]
actually it is 2.6.0

          └─┬ git-stats-importer@2.3.0 
      ├─┬ bug-killer@4.1.0 
      │ ├── ansi-parser@3.0.0 
      │ ├─┬ couleurs@5.0.0 
      │ │ ├── flat-colors@3.0.0 
      │ │ ├── typpy@2.0.0 
      │ │ └── x256@0.0.2 
      │ ├── deffy@2.0.0 
      │ └── typpy@2.0.0 
      ├─┬ clp@3.1.0 
      │ ├── ansi-parser@2.0.0 
      │ ├─┬ le-table@4.0.0 
      │ │ ├─┬ cli-box@5.0.0 
      │ │ │ └─┬ ul@5.0.0 
      │ │ │   └── typpy@2.0.0 
      │ │ ├── overlap@2.0.0 
      │ │ └─┬ ul@5.0.0 
      │ │   └── typpy@2.0.0 
      │ └─┬ ul@5.0.0 
      │   └── typpy@2.0.0 
      ├─┬ git-repos@1.1.0 
      │ ├── abs@1.1.0 
      │ └── findit@2.0.0 
      ├─┬ git-stats@2.6.0 
      │ ├─┬ cli-gh-cal@1.1.0 
      │ │ ├─┬ bug-killer@4.0.0 
      │ │ │ └── typpy@2.0.0 
      │ │ └── git-stats-colors@2.2.0 
      │ ├─┬ cli-pie@2.1.0 
      │ │ ├─┬ cli-circle@3.1.0 
      │ │ │ └─┬ cli-graph@3.1.0 
      │ │ │   └─┬ ul@5.0.0 
      │ │ │     └── typpy@2.0.0 
      │ │ └── flatcolors@3.0.0 
      │ ├── iterate-object@1.2.0 
      │ ├── moment@2.10.6 
      │ ├── r-json@1.1.0 
      │ └── w-json@1.2.0 
      ├─┬ gitlog-parser@0.0.4 
      │ └── byline@4.2.1 
      ├─┬ gry@4.2.0 
      │ └─┬ exec-limiter@3.1.0 
      │   └── limit-it@3.1.0 
      ├── is-there@4.2.0 
      ├── oargv@3.3.0 
      ├── one-by-one@2.1.0 
      ├── parent-search@1.2.0 
      ├── typpy@2.2.0 
      └─┬ ul@5.1.0 
        └── typpy@2.0.0

**Comment by joeyhipolito** [comment]
~ ❯❯❯ node -v
   v5.0.0

**Comment by IonicaBizau** [comment]
@joeyhipolito Does `git-stats-importer -e 'your email'` work?

**Comment by joeyhipolito** [comment]
nope..not at all

**Comment by IonicaBizau** [comment]
@joeyhipolito Addressed in https://github.com/IonicaBizau/git-stats/commit/0208b8239d43e50b4866507fbd9fe3a1473fce25.

Try again to `npm i -g git-stats-importer@latest`.

**Comment by joeyhipolito** [comment]
Looks like it's importing now :)

**Comment by IonicaBizau** [comment]
Wowowow! Finally! :relaxed:

**Comment by joeyhipolito** [comment]
btw

      warn  Failed to read the config file:
       │RangeError: Maximum call stack size exceeded
       │    at GitStats.getConfig

**Comment by IonicaBizau** [comment]
@joeyhipolito When does this appear? Do you have a `~/.git-stats-config.js` file? I remember I fixed it...

**Comment by joeyhipolito** [comment]
yeap, I have, it appears everytime, I execute git-stats, this should be in git-stats issue i suppose

**Comment by IonicaBizau** [comment]
Ohh, I see! Let's move the discussion there, then. :smile:
